# -*- coding: utf-8 -*-
"""Sentiment Analysis for AI Using Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mj090yuyLPUFjifDqg4dxwL6xOgjAkxD
"""

pip install transformers

from transformers import pipeline
classifier=pipeline("sentiment-analysis",
                    model="cardiffnlp/twitter-roberta-base-sentiment")
classifier("I love playing football")